version: '3.9'

services:
  client:
    container_name: galaxy-pizza-client-dev
    image: galaxy-pizza-client-dev
    build:
      context: .
      target: development
    ports:
      - '3000:3000'
    volumes:
      - ./src:/app/src
